### ISSUE TITLE
Add a new dedicated CI workflow for HIP-904 tests

### ISSUE THREAD

**Issue by quiet-node** [hashgraph/hedera-smart-contracts#1170]
### Description

Currently, there is no dedicated CI workflow to specifically run tests for the HIP-904 feature. This lack of separation makes it harder to ensure focused testing and validate changes related to HIP-904 efficiently.

Solution

Introduce a dedicated CI workflow for HIP-904 tests to improve test coverage, streamline validation, and maintain better organization in the CI process. The workflow will automatically execute all unit and acceptance tests relevant to HIP-904 whenever changes are pushed.

1. Add a new job like below to the [tests.yml](https://github.com/hashgraph/hedera-smart-contracts/blob/main/.github/workflows/tests.yml), under the [jobs](https://github.com/hashgraph/hedera-smart-contracts/blob/main/.github/workflows/tests.yml#L23) seciton

```
  HIP904:
    name: HIP904 Contract Test Suite
    uses: ./.github/workflows/test-workflow.yml
    with:
      testfilter: HIP904
```

2. Within the same [tests.yml](https://github.com/hashgraph/hedera-smart-contracts/blob/main/.github/workflows/tests.yml), add the CI job name to the [PublishResults](https://github.com/hashgraph/hedera-smart-contracts/blob/main/.github/workflows/tests.yml#L120-L139) section
